// Code generated by mus-gen. DO NOT EDIT.

package cmds

import (
	"fmt"

	"github.com/cmd-stream/cmd-stream-go/core"
	"github.com/cmd-stream/examples-go/hello-world/receiver"
	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/typed"
)

const (
	SayFancyHelloMultiCmdDTM com.DTM = iota + 1
)

var SayFancyHelloMultiCmdMUS = sayFancyHelloMultiCmdMUS{}

type sayFancyHelloMultiCmdMUS struct{}

func (s sayFancyHelloMultiCmdMUS) Marshal(v SayFancyHelloMultiCmd, w mus.Writer) (n int, err error) {
	return ord.String.Marshal(v.str, w)
}

func (s sayFancyHelloMultiCmdMUS) Unmarshal(r mus.Reader) (v SayFancyHelloMultiCmd, n int, err error) {
	v.str, n, err = ord.String.Unmarshal(r)
	return
}

func (s sayFancyHelloMultiCmdMUS) Size(v SayFancyHelloMultiCmd) (size int) {
	return ord.String.Size(v.str)
}

func (s sayFancyHelloMultiCmdMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = ord.String.Skip(r)
	return
}

var SayFancyHelloMultiCmdTypedMUS = typed.NewTypedSer(SayFancyHelloMultiCmdDTM, SayFancyHelloMultiCmdMUS)

var CmdMUS = cmdMUS{}

type cmdMUS struct{}

func (s cmdMUS) Marshal(v core.Cmd[receiver.Greeter], w mus.Writer) (n int, err error) {
	switch t := v.(type) {
	case SayFancyHelloMultiCmd:
		return SayFancyHelloMultiCmdTypedMUS.Marshal(t, w)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s cmdMUS) Unmarshal(r mus.Reader) (v core.Cmd[receiver.Greeter], n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case SayFancyHelloMultiCmdDTM:
		v, n1, err = SayFancyHelloMultiCmdTypedMUS.UnmarshalData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s cmdMUS) Size(v core.Cmd[receiver.Greeter]) (size int) {
	switch t := v.(type) {
	case SayFancyHelloMultiCmd:
		return SayFancyHelloMultiCmdTypedMUS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s cmdMUS) Skip(r mus.Reader) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case SayFancyHelloMultiCmdDTM:
		n1, err = SayFancyHelloMultiCmdTypedMUS.SkipData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}
