// Code generated by musgen-go. DO NOT EDIT.

package cmds

import (
	"fmt"
	"reflect"

	"github.com/cmd-stream/core-go"
	"github.com/cmd-stream/examples-go/hello-world/receiver"
	com "github.com/mus-format/common-go"
	dts "github.com/mus-format/dts-stream-go"
	exts "github.com/mus-format/ext-mus-stream-go"
	muss "github.com/mus-format/mus-stream-go"
	strops "github.com/mus-format/mus-stream-go/options/string"
	"github.com/mus-format/mus-stream-go/ord"
)

var (
	string6ΣpNH2vVpMrslPPDKNWvGwΞΞ = ord.NewValidStringSer(strops.WithLenValidator(com.ValidatorFn[int](ValidateLength)))
)

var SayHelloCmdMUS = sayHelloCmdMUS{}

type sayHelloCmdMUS struct{}

func (s sayHelloCmdMUS) Marshal(v SayHelloCmd, w muss.Writer) (n int, err error) {
	return string6ΣpNH2vVpMrslPPDKNWvGwΞΞ.Marshal(v.str, w)
}

func (s sayHelloCmdMUS) Unmarshal(r muss.Reader) (v SayHelloCmd, n int, err error) {
	v.str, n, err = string6ΣpNH2vVpMrslPPDKNWvGwΞΞ.Unmarshal(r)
	return
}

func (s sayHelloCmdMUS) Size(v SayHelloCmd) (size int) {
	return string6ΣpNH2vVpMrslPPDKNWvGwΞΞ.Size(v.str)
}

func (s sayHelloCmdMUS) Skip(r muss.Reader) (n int, err error) {
	n, err = string6ΣpNH2vVpMrslPPDKNWvGwΞΞ.Skip(r)
	return
}

var SayHelloCmdDTS = dts.New[SayHelloCmd](SayHelloCmdDTM, SayHelloCmdMUS)

var SayFancyHelloCmdMUS = sayFancyHelloCmdMUS{}

type sayFancyHelloCmdMUS struct{}

func (s sayFancyHelloCmdMUS) Marshal(v SayFancyHelloCmd, w muss.Writer) (n int, err error) {
	return string6ΣpNH2vVpMrslPPDKNWvGwΞΞ.Marshal(v.str, w)
}

func (s sayFancyHelloCmdMUS) Unmarshal(r muss.Reader) (v SayFancyHelloCmd, n int, err error) {
	v.str, n, err = string6ΣpNH2vVpMrslPPDKNWvGwΞΞ.Unmarshal(r)
	return
}

func (s sayFancyHelloCmdMUS) Size(v SayFancyHelloCmd) (size int) {
	return string6ΣpNH2vVpMrslPPDKNWvGwΞΞ.Size(v.str)
}

func (s sayFancyHelloCmdMUS) Skip(r muss.Reader) (n int, err error) {
	n, err = string6ΣpNH2vVpMrslPPDKNWvGwΞΞ.Skip(r)
	return
}

var SayFancyHelloCmdDTS = dts.New[SayFancyHelloCmd](SayFancyHelloCmdDTM, SayFancyHelloCmdMUS)

var CmdMUS = cmdMUS{}

type cmdMUS struct{}

func (s cmdMUS) Marshal(v core.Cmd[receiver.Greeter], w muss.Writer) (n int, err error) {
	if m, ok := v.(exts.MarshallerTypedMUS); ok {
		return m.MarshalTypedMUS(w)
	}
	panic(fmt.Sprintf("%v doesn't implement the exts.MarshallerTypedMUS interface", reflect.TypeOf(v)))
}

func (s cmdMUS) Unmarshal(r muss.Reader) (v core.Cmd[receiver.Greeter], n int, err error) {
	dtm, n, err := dts.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case SayHelloCmdDTM:
		v, n1, err = SayHelloCmdDTS.UnmarshalData(r)
	case SayFancyHelloCmdDTM:
		v, n1, err = SayFancyHelloCmdDTS.UnmarshalData(r)
	default:
		err = fmt.Errorf("unexpected %v DTM", dtm)
		return
	}
	n += n1
	return
}

func (s cmdMUS) Size(v core.Cmd[receiver.Greeter]) (size int) {
	if m, ok := v.(exts.MarshallerTypedMUS); ok {
		return m.SizeTypedMUS()
	}
	panic(fmt.Sprintf("%v doesn't implement the exts.MarshallerTypedMUS interface", reflect.TypeOf(v)))
}

func (s cmdMUS) Skip(r muss.Reader) (n int, err error) {
	dtm, n, err := dts.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case SayHelloCmdDTM:
		n1, err = SayHelloCmdDTS.SkipData(r)
	case SayFancyHelloCmdDTM:
		n1, err = SayFancyHelloCmdDTS.SkipData(r)
	default:
		err = fmt.Errorf("unexpected %v DTM", dtm)
		return
	}
	n += n1
	return
}
