// Code generated by mus-gen. DO NOT EDIT.

package cmds

import (
	"fmt"

	"github.com/cmd-stream/cmd-stream-go/core"
	"github.com/cmd-stream/examples-go/hello-world/receiver"
	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-stream-go"
	stropts "github.com/mus-format/mus-stream-go/options/string"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/typed"
)

const (
	SayHelloCmdDTM com.DTM = iota + 1
	SayFancyHelloCmdDTM
)

var (
	stringkΔf96grJKz3TMΔntiprq9AΞΞ = ord.NewValidStringSer(stropts.WithLenValidator(com.ValidatorFn[int](ValidateLength)))
)

var SayHelloCmdMUS = sayHelloCmdMUS{}

type sayHelloCmdMUS struct{}

func (s sayHelloCmdMUS) Marshal(v SayHelloCmd, w mus.Writer) (n int, err error) {
	return stringkΔf96grJKz3TMΔntiprq9AΞΞ.Marshal(v.Str, w)
}

func (s sayHelloCmdMUS) Unmarshal(r mus.Reader) (v SayHelloCmd, n int, err error) {
	v.Str, n, err = stringkΔf96grJKz3TMΔntiprq9AΞΞ.Unmarshal(r)
	return
}

func (s sayHelloCmdMUS) Size(v SayHelloCmd) (size int) {
	return stringkΔf96grJKz3TMΔntiprq9AΞΞ.Size(v.Str)
}

func (s sayHelloCmdMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = stringkΔf96grJKz3TMΔntiprq9AΞΞ.Skip(r)
	return
}

var SayHelloCmdTypedMUS = typed.NewTypedSer(SayHelloCmdDTM, SayHelloCmdMUS)

var SayFancyHelloCmdMUS = sayFancyHelloCmdMUS{}

type sayFancyHelloCmdMUS struct{}

func (s sayFancyHelloCmdMUS) Marshal(v SayFancyHelloCmd, w mus.Writer) (n int, err error) {
	return stringkΔf96grJKz3TMΔntiprq9AΞΞ.Marshal(v.Str, w)
}

func (s sayFancyHelloCmdMUS) Unmarshal(r mus.Reader) (v SayFancyHelloCmd, n int, err error) {
	v.Str, n, err = stringkΔf96grJKz3TMΔntiprq9AΞΞ.Unmarshal(r)
	return
}

func (s sayFancyHelloCmdMUS) Size(v SayFancyHelloCmd) (size int) {
	return stringkΔf96grJKz3TMΔntiprq9AΞΞ.Size(v.Str)
}

func (s sayFancyHelloCmdMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = stringkΔf96grJKz3TMΔntiprq9AΞΞ.Skip(r)
	return
}

var SayFancyHelloCmdTypedMUS = typed.NewTypedSer(SayFancyHelloCmdDTM, SayFancyHelloCmdMUS)

var CmdMUS = cmdMUS{}

type cmdMUS struct{}

func (s cmdMUS) Marshal(v core.Cmd[receiver.Greeter], w mus.Writer) (n int, err error) {
	switch t := v.(type) {
	case SayHelloCmd:
		return SayHelloCmdTypedMUS.Marshal(t, w)
	case SayFancyHelloCmd:
		return SayFancyHelloCmdTypedMUS.Marshal(t, w)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s cmdMUS) Unmarshal(r mus.Reader) (v core.Cmd[receiver.Greeter], n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case SayHelloCmdDTM:
		v, n1, err = SayHelloCmdTypedMUS.UnmarshalData(r)
	case SayFancyHelloCmdDTM:
		v, n1, err = SayFancyHelloCmdTypedMUS.UnmarshalData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s cmdMUS) Size(v core.Cmd[receiver.Greeter]) (size int) {
	switch t := v.(type) {
	case SayHelloCmd:
		return SayHelloCmdTypedMUS.Size(t)
	case SayFancyHelloCmd:
		return SayFancyHelloCmdTypedMUS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s cmdMUS) Skip(r mus.Reader) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case SayHelloCmdDTM:
		n1, err = SayHelloCmdTypedMUS.SkipData(r)
	case SayFancyHelloCmdDTM:
		n1, err = SayFancyHelloCmdTypedMUS.SkipData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}
