// Code generated by mus-gen. DO NOT EDIT.

package cmds

import (
	"fmt"

	"github.com/cmd-stream/cmd-stream-go/core"
	hwcmds "github.com/cmd-stream/examples-go/hello-world/cmds"
	"github.com/cmd-stream/examples-go/hello-world/receiver"
	otelcmd "github.com/cmd-stream/otelcmd-stream-go"
	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/typed"
)

var (
	map6dq5BnNOv8rljwdF6iTwkwΞΞ = ord.NewMapSer(ord.String, ord.String)
	ptr7zyermuΔ7iG6vcIQ5r9q9wΞΞ = ord.NewPtrSer(map6dq5BnNOv8rljwdF6iTwkwΞΞ)
)

var TraceSayHelloCmdMUS = traceSayHelloCmdMUS{}

type traceSayHelloCmdMUS struct{}

func (s traceSayHelloCmdMUS) Marshal(v otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayHelloCmd], w mus.Writer) (n int, err error) {
	n, err = ptr7zyermuΔ7iG6vcIQ5r9q9wΞΞ.Marshal(v.MapCarrier, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = hwcmds.SayHelloCmdMUS.Marshal(v.Cmd, w)
	n += n1
	return
}

func (s traceSayHelloCmdMUS) Unmarshal(r mus.Reader) (v otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayHelloCmd], n int, err error) {
	v.MapCarrier, n, err = ptr7zyermuΔ7iG6vcIQ5r9q9wΞΞ.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	v.Cmd, n1, err = hwcmds.SayHelloCmdMUS.Unmarshal(r)
	n += n1
	return
}

func (s traceSayHelloCmdMUS) Size(v otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayHelloCmd]) (size int) {
	size = ptr7zyermuΔ7iG6vcIQ5r9q9wΞΞ.Size(v.MapCarrier)
	return size + hwcmds.SayHelloCmdMUS.Size(v.Cmd)
}

func (s traceSayHelloCmdMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = ptr7zyermuΔ7iG6vcIQ5r9q9wΞΞ.Skip(r)
	if err != nil {
		return
	}
	var n1 int
	n1, err = hwcmds.SayHelloCmdMUS.Skip(r)
	n += n1
	return
}

var TraceSayHelloCmdTypedMUS = typed.NewSer(TraceSayHelloCmdDTM, TraceSayHelloCmdMUS)

var TraceSayFancyHelloCmdMUS = traceSayFancyHelloCmdMUS{}

type traceSayFancyHelloCmdMUS struct{}

func (s traceSayFancyHelloCmdMUS) Marshal(v otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayFancyHelloCmd], w mus.Writer) (n int, err error) {
	n, err = ptr7zyermuΔ7iG6vcIQ5r9q9wΞΞ.Marshal(v.MapCarrier, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = hwcmds.SayFancyHelloCmdMUS.Marshal(v.Cmd, w)
	n += n1
	return
}

func (s traceSayFancyHelloCmdMUS) Unmarshal(r mus.Reader) (v otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayFancyHelloCmd], n int, err error) {
	v.MapCarrier, n, err = ptr7zyermuΔ7iG6vcIQ5r9q9wΞΞ.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	v.Cmd, n1, err = hwcmds.SayFancyHelloCmdMUS.Unmarshal(r)
	n += n1
	return
}

func (s traceSayFancyHelloCmdMUS) Size(v otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayFancyHelloCmd]) (size int) {
	size = ptr7zyermuΔ7iG6vcIQ5r9q9wΞΞ.Size(v.MapCarrier)
	return size + hwcmds.SayFancyHelloCmdMUS.Size(v.Cmd)
}

func (s traceSayFancyHelloCmdMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = ptr7zyermuΔ7iG6vcIQ5r9q9wΞΞ.Skip(r)
	if err != nil {
		return
	}
	var n1 int
	n1, err = hwcmds.SayFancyHelloCmdMUS.Skip(r)
	n += n1
	return
}

var TraceSayFancyHelloCmdTypedMUS = typed.NewSer(TraceSayFancyHelloCmdDTM, TraceSayFancyHelloCmdMUS)

var CmdMUS = cmdMUS{}

type cmdMUS struct{}

func (s cmdMUS) Marshal(v core.Cmd[receiver.Greeter], w mus.Writer) (n int, err error) {
	switch t := v.(type) {
	case otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayHelloCmd]:
		return TraceSayHelloCmdTypedMUS.Marshal(t, w)
	case otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayFancyHelloCmd]:
		return TraceSayFancyHelloCmdTypedMUS.Marshal(t, w)
	case hwcmds.SayHelloCmd:
		return hwcmds.SayHelloCmdTypedMUS.Marshal(t, w)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s cmdMUS) Unmarshal(r mus.Reader) (v core.Cmd[receiver.Greeter], n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case TraceSayHelloCmdDTM:
		v, n1, err = TraceSayHelloCmdTypedMUS.UnmarshalData(r)
	case TraceSayFancyHelloCmdDTM:
		v, n1, err = TraceSayFancyHelloCmdTypedMUS.UnmarshalData(r)
	case hwcmds.SayHelloCmdDTM:
		v, n1, err = hwcmds.SayHelloCmdTypedMUS.UnmarshalData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s cmdMUS) Size(v core.Cmd[receiver.Greeter]) (size int) {
	switch t := v.(type) {
	case otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayHelloCmd]:
		return TraceSayHelloCmdTypedMUS.Size(t)
	case otelcmd.TraceCmd[receiver.Greeter, hwcmds.SayFancyHelloCmd]:
		return TraceSayFancyHelloCmdTypedMUS.Size(t)
	case hwcmds.SayHelloCmd:
		return hwcmds.SayHelloCmdTypedMUS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s cmdMUS) Skip(r mus.Reader) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case TraceSayHelloCmdDTM:
		n1, err = TraceSayHelloCmdTypedMUS.SkipData(r)
	case TraceSayFancyHelloCmdDTM:
		n1, err = TraceSayFancyHelloCmdTypedMUS.SkipData(r)
	case hwcmds.SayHelloCmdDTM:
		n1, err = hwcmds.SayHelloCmdTypedMUS.SkipData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}
