// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.10
// source: cmds/cmds.proto

package cmds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCmd) Reset() {
	*x = AddCmd{}
	mi := &file_cmds_cmds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCmd) ProtoMessage() {}

func (x *AddCmd) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_cmds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCmd.ProtoReflect.Descriptor instead.
func (*AddCmd) Descriptor() ([]byte, []int) {
	return file_cmds_cmds_proto_rawDescGZIP(), []int{0}
}

func (x *AddCmd) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddCmd) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type SubCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=A,proto3" json:"A,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=B,proto3" json:"B,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCmd) Reset() {
	*x = SubCmd{}
	mi := &file_cmds_cmds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCmd) ProtoMessage() {}

func (x *SubCmd) ProtoReflect() protoreflect.Message {
	mi := &file_cmds_cmds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCmd.ProtoReflect.Descriptor instead.
func (*SubCmd) Descriptor() ([]byte, []int) {
	return file_cmds_cmds_proto_rawDescGZIP(), []int{1}
}

func (x *SubCmd) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *SubCmd) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

var File_cmds_cmds_proto protoreflect.FileDescriptor

const file_cmds_cmds_proto_rawDesc = "" +
	"\n" +
	"\x0fcmds/cmds.proto\x12\bprotobuf\"$\n" +
	"\x06AddCmd\x12\f\n" +
	"\x01A\x18\x01 \x01(\x03R\x01A\x12\f\n" +
	"\x01B\x18\x02 \x01(\x03R\x01B\"$\n" +
	"\x06SubCmd\x12\f\n" +
	"\x01A\x18\x01 \x01(\x03R\x01A\x12\f\n" +
	"\x01B\x18\x02 \x01(\x03R\x01BB6Z4github.com/cmd-stream/examples-go/calc_protobuf/cmdsb\x06proto3"

var (
	file_cmds_cmds_proto_rawDescOnce sync.Once
	file_cmds_cmds_proto_rawDescData []byte
)

func file_cmds_cmds_proto_rawDescGZIP() []byte {
	file_cmds_cmds_proto_rawDescOnce.Do(func() {
		file_cmds_cmds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmds_cmds_proto_rawDesc), len(file_cmds_cmds_proto_rawDesc)))
	})
	return file_cmds_cmds_proto_rawDescData
}

var file_cmds_cmds_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmds_cmds_proto_goTypes = []any{
	(*AddCmd)(nil), // 0: protobuf.AddCmd
	(*SubCmd)(nil), // 1: protobuf.SubCmd
}
var file_cmds_cmds_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmds_cmds_proto_init() }
func file_cmds_cmds_proto_init() {
	if File_cmds_cmds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmds_cmds_proto_rawDesc), len(file_cmds_cmds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmds_cmds_proto_goTypes,
		DependencyIndexes: file_cmds_cmds_proto_depIdxs,
		MessageInfos:      file_cmds_cmds_proto_msgTypes,
	}.Build()
	File_cmds_cmds_proto = out.File
	file_cmds_cmds_proto_goTypes = nil
	file_cmds_cmds_proto_depIdxs = nil
}
